import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { findRuntimeTypesDrift } from "./runtime-types-drift";

const ROOT = join(import.meta.dirname, "..");

const fixtures: string[] = [];

afterEach(() => {
	for (const fixture of fixtures.splice(0)) rmSync(fixture, { recursive: true, force: true });
});

const WORKERD = "1.20260721.1";

/** A Worker whose committed runtime types were generated from its own config. */
const BASELINE: Record<string, string> = {
	"apps/data-service/package.json": JSON.stringify({ name: "data-service" }),
	"apps/data-service/wrangler.jsonc": [
		"{",
		'\t"name": "fixture",',
		'\t// "compatibility_date": "2020-01-01",',
		'\t"compatibility_date": "2026-07-08",',
		'\t"compatibility_flags": ["nodejs_compat"]',
		"}",
	].join("\n"),
	"apps/data-service/worker-configuration.d.ts": [
		"/* eslint-disable */",
		"// Generated by Wrangler by running `wrangler types` (hash: abc123)",
		`// Runtime types generated with workerd@${WORKERD} 2026-07-08 nodejs_compat`,
		"interface Env {}",
	].join("\n"),
	// The toolchain the committed types claim to have been generated by.
	"apps/data-service/node_modules/wrangler/package.json": JSON.stringify({
		name: "wrangler",
		version: "4.113.0",
	}),
	"apps/data-service/node_modules/workerd/package.json": JSON.stringify({
		name: "workerd",
		version: WORKERD,
	}),
};

function makeFixture(overrides: Record<string, string | null> = {}): string {
	const dir = mkdtempSync(join(tmpdir(), "runtime-types-"));
	fixtures.push(dir);

	const files: Record<string, string | null> = { ...BASELINE, ...overrides };
	for (const [relPath, contents] of Object.entries(files)) {
		if (contents === null) continue;
		const full = join(dir, relPath);
		mkdirSync(dirname(full), { recursive: true });
		writeFileSync(full, contents);
	}
	return dir;
}

const kinds = (dir: string) => findRuntimeTypesDrift(dir).map((issue) => issue.kind);

describe("findRuntimeTypesDrift", () => {
	it("reports nothing when the committed types match the configured Worker", () => {
		expect(findRuntimeTypesDrift(makeFixture())).toEqual([]);
	});

	it("fails when the compatibility date is bumped without regenerating types", () => {
		const dir = makeFixture({
			"apps/data-service/wrangler.jsonc": BASELINE["apps/data-service/wrangler.jsonc"]?.replace(
				'"compatibility_date": "2026-07-08"',
				'"compatibility_date": "2026-11-01"',
			) as string,
		});

		expect(kinds(dir)).toContain("compatibility_date");
	});

	it("passes again once the types are regenerated for the new date", () => {
		const dir = makeFixture({
			"apps/data-service/wrangler.jsonc": BASELINE["apps/data-service/wrangler.jsonc"]?.replace(
				'"compatibility_date": "2026-07-08"',
				'"compatibility_date": "2026-11-01"',
			) as string,
			"apps/data-service/worker-configuration.d.ts": BASELINE[
				"apps/data-service/worker-configuration.d.ts"
			]?.replace("2026-07-08", "2026-11-01") as string,
		});

		expect(findRuntimeTypesDrift(dir)).toEqual([]);
	});

	it("ignores a commented-out compatibility date", () => {
		// The bump workflow rewrites only active lines; the check must read the
		// same line the runtime does.
		expect(findRuntimeTypesDrift(makeFixture())).toEqual([]);
	});

	it("fails when the compatibility flags diverge", () => {
		const dir = makeFixture({
			"apps/data-service/wrangler.jsonc": BASELINE["apps/data-service/wrangler.jsonc"]?.replace(
				'["nodejs_compat"]',
				'["nodejs_compat", "no_nodejs_compat_v2"]',
			) as string,
		});

		expect(kinds(dir)).toContain("compatibility_flags");
	});

	it("fails when the workerd toolchain has moved on", () => {
		const dir = makeFixture({
			"apps/data-service/node_modules/workerd/package.json": JSON.stringify({
				name: "workerd",
				version: "1.20261201.0",
			}),
		});

		expect(kinds(dir)).toContain("workerd");
	});

	it("fails when the type definitions are missing entirely", () => {
		const dir = makeFixture({ "apps/data-service/worker-configuration.d.ts": null });

		expect(kinds(dir)).toContain("missing");
	});

	it("fails when the banner cannot be read", () => {
		const dir = makeFixture({
			"apps/data-service/worker-configuration.d.ts": "interface Env {}",
		});

		expect(kinds(dir)).toContain("unreadable");
	});

	it("names the command that fixes the drift", () => {
		const dir = makeFixture({
			"apps/data-service/wrangler.jsonc": BASELINE["apps/data-service/wrangler.jsonc"]?.replace(
				'"compatibility_date": "2026-07-08"',
				'"compatibility_date": "2026-11-01"',
			) as string,
		});

		const [issue] = findRuntimeTypesDrift(dir);
		expect(issue?.remedy).toBe("pnpm --filter data-service cf-typegen");
	});
});

describe("this repository", () => {
	it("has runtime types matching its configured compatibility date and toolchain", () => {
		expect(findRuntimeTypesDrift(ROOT)).toEqual([]);
	});
});
